// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +xforza -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV64XFORZA

// RV64XFORZA-LABEL: @quit(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.quit()
void quit(){
  __forza_quit();
}

// RV64XFORZA-LABEL: @resched(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.resched()
void resched(){
  __forza_resched();
}

// RV64XFORZA-LABEL: @spawn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.spawn(ptr %pc, ptr %stack)
unsigned long int spawn(unsigned long *pc, unsigned long *stack){
  return __forza_spawn(pc,stack);
}

// RV64XFORZA-LABEL: @mcopy(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.mcopy(ptr %dest, ptr %src, i64 %sz)
void mcopy(unsigned long *dest, unsigned long *src, unsigned long sz){
  __forza_mcopy(dest, src, sz);
}

// RV64XFORZA-LABEL: @fence_test(
// RV64XFORZA-NEXT:  entry:
// CHECK:  [[TMP0:%.*]] = call void @llvm.riscv.forza.amo.r.add64u(ptr %0, i64 %1)
// CHECK:  call void @llvm.riscv.forza.fence()
void fence_test(long *a, unsigned long b){
  __forza_amo_r_add64u(a,b);
  __forza_fence();
}
