// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +xforza -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV64XFORZA

// RV64XFORZA-LABEL: @quit(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.quit()
void quit(){
  __forza_quit();
}

// RV64XFORZA-LABEL: @resched(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.resched()
void resched(){
  __forza_resched();
}

// RV64XFORZA-LABEL: @spawn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.spawn(ptr %pc, ptr %stack)
unsigned long int spawn(unsigned long *pc, unsigned long *stack){
  return __forza_spawn(pc,stack);
}
