// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +xforza -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV64XFORZA


// RV64XFORZA-LABEL: @amo_r_add8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.add8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_add8u(long int *a, char b){
  __forza_amo_r_add8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.sub8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_sub8u(long int *a, char b){
  __forza_amo_r_sub8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.add16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_add16u(long int *a, short b){
  __forza_amo_r_add16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.sub16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_sub16u(long int *a, short b){
  __forza_amo_r_sub16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.add32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_add32u(int *a, int b){
  __forza_amo_r_add32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.sub32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_sub32u(int *a, int b){
  __forza_amo_r_sub32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.add64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_add64u(long int *a, long int b){
  __forza_amo_r_add64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.sub64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_sub64u(long int *a, long int b){
  __forza_amo_r_sub64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.and8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_and8u(long int *a, char b){
  __forza_amo_r_and8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.and16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_and16u(long int *a, short b){
  __forza_amo_r_and16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.and32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_and32u(int *a, int b){
  __forza_amo_r_and32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.and64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_and64u(long int *a, long int b){
  __forza_amo_r_and64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.or8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_or8u(long int *a, char b){
  __forza_amo_r_or8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.or16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
short amo_r_or16u(long int *a, short b){
   __forza_amo_r_or16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.or32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_or32u(int *a, int b){
   __forza_amo_r_or32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.or64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_or64u(long int *a, long int b){
   __forza_amo_r_or64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.xor8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_xor8u(long int *a, char b){
   __forza_amo_r_xor8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.xor16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_xor16u(long int *a, short b){
   __forza_amo_r_xor16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.xor32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_xor32u(int *a, int b){
   __forza_amo_r_xor32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.xor64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_xor64u(long int *a, long int b){
   __forza_amo_r_xor64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smax8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_smax8u(long int *a, char b){
   __forza_amo_r_smax8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smax16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_smax16u(long int *a, short b){
   __forza_amo_r_smax16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smax32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_smax32u(int *a, int b){
   __forza_amo_r_smax32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smax64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_smax64u(long int *a, long int b){
   __forza_amo_r_smax64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umax8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_umax8u(unsigned long *a, char b){
   __forza_amo_r_umax8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umax16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_umax16u(unsigned long *a, short b){
   __forza_amo_r_umax16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umax32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_umax32u(unsigned int *a, int b){
   __forza_amo_r_umax32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umax64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_umax64u(unsigned long *a, long int b){
   __forza_amo_r_umax64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smin8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_smin8u(long *a, char b){
   __forza_amo_r_smin8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smin16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_smin16u(long int *a, short b){
   __forza_amo_r_smin16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smin32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_smin32u(int *a, int b){
   __forza_amo_r_smin32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.smin64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_smin64u(long int *a, long int b){
   __forza_amo_r_smin64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umin8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_umin8u(unsigned long *a, char b){
   __forza_amo_r_umin8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umin16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_umin16u(unsigned long *a, short b){
   __forza_amo_r_umin16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umin32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_umin32u(unsigned int *a, int b){
   __forza_amo_r_umin32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.umin64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_umin64u(unsigned long *a, long int b){
   __forza_amo_r_umin64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i8 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.thrs8u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_thrs8u(long int *a, char b){
   __forza_amo_r_thrs8u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  %conv = sext i16 %b to i64
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.thrs16u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_thrs16u(long int *a, short b){
   __forza_amo_r_thrs16u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.thrs32u(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
void amo_r_thrs32u(int *a, int b){
   __forza_amo_r_thrs32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.thrs64u(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
void amo_r_thrs64u(long int *a, long int b){
   __forza_amo_r_thrs64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.add8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_add8migr_nn(char *a, char b){
  return __forza_amo_r_add8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.add16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_add16migr_nn(short *a, short b){
  return __forza_amo_r_add16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.add32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_add32migr_nn(int *a, int b){
  return __forza_amo_r_add32migr_nn(a,b);
}

// -- amo_r_add64migr_nn
// RV64XFORZA-LABEL: @amo_r_add64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.add64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_add64migr_nn(long int *a, long int b){
  return __forza_amo_r_add64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.and8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_and8migr_nn(char *a, char b){
  return __forza_amo_r_and8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.and16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_and16migr_nn(short *a, short b){
  return __forza_amo_r_and16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.and32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_and32migr_nn(int *a, int b){
  return __forza_amo_r_and32migr_nn(a,b);
}

// -- amo_r_and64migr_nn
// RV64XFORZA-LABEL: @amo_r_and64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.and64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_and64migr_nn(long int *a, long int b){
  return __forza_amo_r_and64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.or8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_or8migr_nn(char *a, char b){
  return __forza_amo_r_or8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.or16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_or16migr_nn(short *a, short b){
  return __forza_amo_r_or16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.or32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_or32migr_nn(int *a, int b){
  return __forza_amo_r_or32migr_nn(a,b);
}

// -- amo_r_or64migr_nn
// RV64XFORZA-LABEL: @amo_r_or64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.or64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_or64migr_nn(long int *a, long int b){
  return __forza_amo_r_or64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.xor8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_xor8migr_nn(char *a, char b){
  return __forza_amo_r_xor8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.xor16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_xor16migr_nn(short *a, short b){
  return __forza_amo_r_xor16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.xor32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_xor32migr_nn(int *a, int b){
  return __forza_amo_r_xor32migr_nn(a,b);
}

// -- amo_r_xor64migr_nn
// RV64XFORZA-LABEL: @amo_r_xor64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.xor64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_xor64migr_nn(long int *a, long int b){
  return __forza_amo_r_xor64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smax8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smax8migr_nn(char *a, char b){
  return __forza_amo_r_smax8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smax16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smax16migr_nn(short *a, short b){
  return __forza_amo_r_smax16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smax32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smax32migr_nn(int *a, int b){
  return __forza_amo_r_smax32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smax64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smax64migr_nn(long int *a, long int b){
  return __forza_amo_r_smax64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umax8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umax8migr_nn(unsigned char *a, char b){
  return __forza_amo_r_umax8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umax16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umax16migr_nn(unsigned short *a, short b){
  return __forza_amo_r_umax16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umax32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umax32migr_nn(unsigned int *a, int b){
  return __forza_amo_r_umax32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umax64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umax64migr_nn(unsigned long int *a, long int b){
  return __forza_amo_r_umax64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smin8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smin8migr_nn(char *a, char b){
  return __forza_amo_r_smin8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smin16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smin16migr_nn(short *a, short b){
  return __forza_amo_r_smin16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smin32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smin32migr_nn(int *a, int b){
  return __forza_amo_r_smin32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smin64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smin64migr_nn(long int *a, long int b){
  return __forza_amo_r_smin64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umin8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umin8migr_nn(unsigned char *a, char b){
  return __forza_amo_r_umin8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umin16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umin16migr_nn(unsigned short *a, short b){
  return __forza_amo_r_umin16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umin32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umin32migr_nn(unsigned int *a, int b){
  return __forza_amo_r_umin32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umin64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umin64migr_nn(unsigned long int *a, long int b){
  return __forza_amo_r_umin64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.thrs8migr.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_thrs8migr_nn(char *a, char b){
  return __forza_amo_r_thrs8migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.thrs16migr.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_thrs16migr_nn(short *a, short b){
  return __forza_amo_r_thrs16migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.thrs32migr.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_thrs32migr_nn(int *a, int b){
  return __forza_amo_r_thrs32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.thrs64migr.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_thrs64migr_nn(long int *a, long int b){
  return __forza_amo_r_thrs64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.add8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_add8migr_on(char *a, char b){
  return __forza_amo_r_add8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.add16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_add16migr_on(short *a, short b){
  return __forza_amo_r_add16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.add32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_add32migr_on(int *a, int b){
  return __forza_amo_r_add32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.add64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_add64migr_on(long int *a, long int b){
  return __forza_amo_r_add64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.and8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_and8migr_on(char *a, char b){
  return __forza_amo_r_and8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.and16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_and16migr_on(short *a, short b){
  return __forza_amo_r_and16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.and32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_and32migr_on(int *a, int b){
  return __forza_amo_r_and32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.and64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_and64migr_on(long int *a, long int b){
  return __forza_amo_r_and64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.or8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_or8migr_on(char *a, char b){
  return __forza_amo_r_or8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.or16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_or16migr_on(short *a, short b){
  return __forza_amo_r_or16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.or32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_or32migr_on(int *a, int b){
  return __forza_amo_r_or32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.or64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_or64migr_on(long int *a, long int b){
  return __forza_amo_r_or64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.xor8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_xor8migr_on(char *a, char b){
  return __forza_amo_r_xor8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.xor16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_xor16migr_on(short *a, short b){
  return __forza_amo_r_xor16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.xor32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_xor32migr_on(int *a, int b){
  return __forza_amo_r_xor32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.xor64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_xor64migr_on(long int *a, long int b){
  return __forza_amo_r_xor64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smax8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smax8migr_on(char *a, char b){
  return __forza_amo_r_smax8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smax16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smax16migr_on(short *a, short b){
  return __forza_amo_r_smax16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smax32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smax32migr_on(int *a, int b){
  return __forza_amo_r_smax32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smax64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smax64migr_on(long int *a, long int b){
  return __forza_amo_r_smax64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umax8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umax8migr_on(unsigned char *a, char b){
  return __forza_amo_r_umax8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umax16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umax16migr_on(unsigned short *a, short b){
  return __forza_amo_r_umax16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umax32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umax32migr_on(unsigned int *a, int b){
  return __forza_amo_r_umax32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umax64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umax64migr_on(unsigned long int *a, long int b){
  return __forza_amo_r_umax64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smin8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smin8migr_on(char *a, char b){
  return __forza_amo_r_smin8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smin16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smin16migr_on(short *a, short b){
  return __forza_amo_r_smin16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smin32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smin32migr_on(int *a, int b){
  return __forza_amo_r_smin32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smin64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smin64migr_on(long int *a, long int b){
  return __forza_amo_r_smin64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umin8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umin8migr_on(unsigned char *a, char b){
  return __forza_amo_r_umin8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umin16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umin16migr_on(unsigned short *a, short b){
  return __forza_amo_r_umin16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umin32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umin32migr_on(unsigned int *a, int b){
  return __forza_amo_r_umin32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umin64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umin64migr_on(unsigned long int *a, long int b){
  return __forza_amo_r_umin64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.thrs8migr.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_thrs8migr_on(char *a, char b){
  return __forza_amo_r_thrs8migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.thrs16migr.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_thrs16migr_on(short *a, short b){
  return __forza_amo_r_thrs16migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.thrs32migr.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_thrs32migr_on(int *a, int b){
  return __forza_amo_r_thrs32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.thrs64migr.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_thrs64migr_on(long int *a, long int b){
  return __forza_amo_r_thrs64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.add8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_add8migr_no(char *a, char b){
  return __forza_amo_r_add8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.add16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_add16migr_no(short *a, short b){
  return __forza_amo_r_add16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.add32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_add32migr_no(int *a, int b){
  return __forza_amo_r_add32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.add64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_add64migr_no(long int *a, long int b){
  return __forza_amo_r_add64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.and8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_and8migr_no(char *a, char b){
  return __forza_amo_r_and8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.and16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_and16migr_no(short *a, short b){
  return __forza_amo_r_and16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.and32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_and32migr_no(int *a, int b){
  return __forza_amo_r_and32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.and64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_and64migr_no(long int *a, long int b){
  return __forza_amo_r_and64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.or8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_or8migr_no(char *a, char b){
  return __forza_amo_r_or8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.or16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_or16migr_no(short *a, short b){
  return __forza_amo_r_or16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.or32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_or32migr_no(int *a, int b){
  return __forza_amo_r_or32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.or64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_or64migr_no(long int *a, long int b){
  return __forza_amo_r_or64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.xor8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_xor8migr_no(char *a, char b){
  return __forza_amo_r_xor8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.xor16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_xor16migr_no(short *a, short b){
  return __forza_amo_r_xor16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.xor32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_xor32migr_no(int *a, int b){
  return __forza_amo_r_xor32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.xor64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_xor64migr_no(long int *a, long int b){
  return __forza_amo_r_xor64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smax8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smax8migr_no(char *a, char b){
  return __forza_amo_r_smax8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smax16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smax16migr_no(short *a, short b){
  return __forza_amo_r_smax16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smax32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smax32migr_no(int *a, int b){
  return __forza_amo_r_smax32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smax64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smax64migr_no(long int *a, long int b){
  return __forza_amo_r_smax64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umax8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umax8migr_no(unsigned char *a, char b){
  return __forza_amo_r_umax8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umax16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umax16migr_no(unsigned short *a, short b){
  return __forza_amo_r_umax16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umax32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umax32migr_no(unsigned int *a, int b){
  return __forza_amo_r_umax32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umax64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umax64migr_no(unsigned long int *a, long int b){
  return __forza_amo_r_umax64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smin8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smin8migr_no(char *a, char b){
  return __forza_amo_r_smin8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smin16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smin16migr_no(short *a, short b){
  return __forza_amo_r_smin16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smin32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smin32migr_no(int *a, int b){
  return __forza_amo_r_smin32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smin64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smin64migr_no(long int *a, long int b){
  return __forza_amo_r_smin64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umin8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umin8migr_no(unsigned char *a, char b){
  return __forza_amo_r_umin8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umin16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umin16migr_no(unsigned short *a, short b){
  return __forza_amo_r_umin16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umin32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umin32migr_no(unsigned int *a, int b){
  return __forza_amo_r_umin32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umin64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umin64migr_no(unsigned long int *a, long int b){
  return __forza_amo_r_umin64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.thrs8migr.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_thrs8migr_no(char *a, char b){
  return __forza_amo_r_thrs8migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.thrs16migr.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_thrs16migr_no(short *a, short b){
  return __forza_amo_r_thrs16migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.thrs32migr.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_thrs32migr_no(int *a, int b){
  return __forza_amo_r_thrs32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.thrs64migr.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_thrs64migr_no(long int *a, long int b){
  return __forza_amo_r_thrs64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.add8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_add8rem_nn(char *a, char b){
  return __forza_amo_r_add8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.add16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_add16rem_nn(short *a, short b){
  return __forza_amo_r_add16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.add32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_add32rem_nn(int *a, int b){
  return __forza_amo_r_add32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.add64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_add64rem_nn(long int *a, long int b){
  return __forza_amo_r_add64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.sub8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_sub8rem_nn(char *a, char b){
  return __forza_amo_r_sub8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.sub16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_sub16rem_nn(short *a, short b){
  return __forza_amo_r_sub16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.sub32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_sub32rem_nn(int *a, int b){
  return __forza_amo_r_sub32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.sub64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_sub64rem_nn(long int *a, long int b){
  return __forza_amo_r_sub64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.and8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_and8rem_nn(char *a, char b){
  return __forza_amo_r_and8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.and16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_and16rem_nn(short *a, short b){
  return __forza_amo_r_and16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.and32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_and32rem_nn(int *a, int b){
  return __forza_amo_r_and32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.and64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_and64rem_nn(long int *a, long int b){
  return __forza_amo_r_and64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.or8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_or8rem_nn(char *a, char b){
  return __forza_amo_r_or8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.or16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_or16rem_nn(short *a, short b){
  return __forza_amo_r_or16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.or32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_or32rem_nn(int *a, int b){
  return __forza_amo_r_or32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.or64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_or64rem_nn(long int *a, long int b){
  return __forza_amo_r_or64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.xor8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_xor8rem_nn(char *a, char b){
  return __forza_amo_r_xor8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.xor16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_xor16rem_nn(short *a, short b){
  return __forza_amo_r_xor16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.xor32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_xor32rem_nn(int *a, int b){
  return __forza_amo_r_xor32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.xor64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_xor64rem_nn(long int *a, long int b){
  return __forza_amo_r_xor64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smax8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smax8rem_nn(char *a, char b){
  return __forza_amo_r_smax8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smax16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smax16rem_nn(short *a, short b){
  return __forza_amo_r_smax16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smax32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smax32rem_nn(int *a, int b){
  return __forza_amo_r_smax32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smax64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smax64rem_nn(long int *a, long int b){
  return __forza_amo_r_smax64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umax8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umax8rem_nn(unsigned char *a, char b){
  return __forza_amo_r_umax8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umax16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umax16rem_nn(unsigned short *a, short b){
  return __forza_amo_r_umax16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umax32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umax32rem_nn(unsigned int *a, int b){
  return __forza_amo_r_umax32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umax64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umax64rem_nn(unsigned long int *a, long int b){
  return __forza_amo_r_umax64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smin8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smin8rem_nn(char *a, char b){
  return __forza_amo_r_smin8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smin16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smin16rem_nn(short *a, short b){
  return __forza_amo_r_smin16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smin32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smin32rem_nn(int *a, int b){
  return __forza_amo_r_smin32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smin64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smin64rem_nn(long int *a, long int b){
  return __forza_amo_r_smin64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umin8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umin8rem_nn(unsigned char *a, char b){
  return __forza_amo_r_umin8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umin16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umin16rem_nn(unsigned short *a, short b){
  return __forza_amo_r_umin16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umin32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umin32rem_nn(unsigned int *a, int b){
  return __forza_amo_r_umin32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umin64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umin64rem_nn(unsigned long int *a, long int b){
  return __forza_amo_r_umin64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.thrs8rem.nn(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_thrs8rem_nn(char *a, char b){
  return __forza_amo_r_thrs8rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.thrs16rem.nn(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_thrs16rem_nn(short *a, short b){
  return __forza_amo_r_thrs16rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.thrs32rem.nn(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_thrs32rem_nn(int *a, int b){
  return __forza_amo_r_thrs32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.thrs64rem.nn(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_thrs64rem_nn(long int *a, long int b){
  return __forza_amo_r_thrs64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.add8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_add8rem_on(char *a, char b){
  return __forza_amo_r_add8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.add16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_add16rem_on(short *a, short b){
  return __forza_amo_r_add16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.add32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_add32rem_on(int *a, int b){
  return __forza_amo_r_add32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.add64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_add64rem_on(long int *a, long int b){
  return __forza_amo_r_add64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.sub8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_sub8rem_on(char *a, char b){
  return __forza_amo_r_sub8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.sub16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_sub16rem_on(short *a, short b){
  return __forza_amo_r_sub16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.sub32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_sub32rem_on(int *a, int b){
  return __forza_amo_r_sub32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.sub64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_sub64rem_on(long int *a, long int b){
  return __forza_amo_r_sub64rem_on(a,b);
}


// RV64XFORZA-LABEL: @amo_r_and8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.and8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_and8rem_on(char *a, char b){
  return __forza_amo_r_and8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.and16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_and16rem_on(short *a, short b){
  return __forza_amo_r_and16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.and32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_and32rem_on(int *a, int b){
  return __forza_amo_r_and32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.and64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_and64rem_on(long int *a, long int b){
  return __forza_amo_r_and64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.or8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_or8rem_on(char *a, char b){
  return __forza_amo_r_or8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.or16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_or16rem_on(short *a, short b){
  return __forza_amo_r_or16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.or32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_or32rem_on(int *a, int b){
  return __forza_amo_r_or32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.or64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_or64rem_on(long int *a, long int b){
  return __forza_amo_r_or64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.xor8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_xor8rem_on(char *a, char b){
  return __forza_amo_r_xor8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.xor16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_xor16rem_on(short *a, short b){
  return __forza_amo_r_xor16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.xor32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_xor32rem_on(int *a, int b){
  return __forza_amo_r_xor32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.xor64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_xor64rem_on(long int *a, long int b){
  return __forza_amo_r_xor64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smax8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smax8rem_on(char *a, char b){
  return __forza_amo_r_smax8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smax16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smax16rem_on(short *a, short b){
  return __forza_amo_r_smax16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smax32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smax32rem_on(int *a, int b){
  return __forza_amo_r_smax32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smax64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smax64rem_on(long int *a, long int b){
  return __forza_amo_r_smax64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umax8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umax8rem_on(unsigned char *a, char b){
  return __forza_amo_r_umax8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umax16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umax16rem_on(unsigned short *a, short b){
  return __forza_amo_r_umax16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umax32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umax32rem_on(unsigned int *a, int b){
  return __forza_amo_r_umax32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umax64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umax64rem_on(unsigned long int *a, long int b){
  return __forza_amo_r_umax64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smin8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smin8rem_on(char *a, char b){
  return __forza_amo_r_smin8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smin16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smin16rem_on(short *a, short b){
  return __forza_amo_r_smin16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smin32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smin32rem_on(int *a, int b){
  return __forza_amo_r_smin32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smin64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smin64rem_on(long int *a, long int b){
  return __forza_amo_r_smin64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umin8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umin8rem_on(unsigned char *a, char b){
  return __forza_amo_r_umin8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umin16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umin16rem_on(unsigned short *a, short b){
  return __forza_amo_r_umin16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umin32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umin32rem_on(unsigned int *a, int b){
  return __forza_amo_r_umin32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umin64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umin64rem_on(unsigned long int *a, long int b){
  return __forza_amo_r_umin64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.thrs8rem.on(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_thrs8rem_on(char *a, char b){
  return __forza_amo_r_thrs8rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.thrs16rem.on(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_thrs16rem_on(short *a, short b){
  return __forza_amo_r_thrs16rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.thrs32rem.on(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_thrs32rem_on(int *a, int b){
  return __forza_amo_r_thrs32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.thrs64rem.on(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_thrs64rem_on(long int *a, long int b){
  return __forza_amo_r_thrs64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.add8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_add8rem_no(char *a, char b){
  return __forza_amo_r_add8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.add16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_add16rem_no(short *a, short b){
  return __forza_amo_r_add16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.add32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_add32rem_no(int *a, int b){
  return __forza_amo_r_add32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_add64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.add64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_add64rem_no(long int *a, long int b){
  return __forza_amo_r_add64rem_no(a,b);
}
// RV64XFORZA-LABEL: @amo_r_sub8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.sub8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_sub8rem_no(char *a, char b){
  return __forza_amo_r_sub8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.sub16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_sub16rem_no(short *a, short b){
  return __forza_amo_r_sub16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.sub32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_sub32rem_no(int *a, int b){
  return __forza_amo_r_sub32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_sub64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.sub64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_sub64rem_no(long int *a, long int b){
  return __forza_amo_r_sub64rem_no(a,b);
}


// RV64XFORZA-LABEL: @amo_r_and8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.and8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_and8rem_no(char *a, char b){
  return __forza_amo_r_and8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.and16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_and16rem_no(short *a, short b){
  return __forza_amo_r_and16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.and32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_and32rem_no(int *a, int b){
  return __forza_amo_r_and32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_and64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.and64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_and64rem_no(long int *a, long int b){
  return __forza_amo_r_and64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.or8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_or8rem_no(char *a, char b){
  return __forza_amo_r_or8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.or16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_or16rem_no(short *a, short b){
  return __forza_amo_r_or16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.or32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_or32rem_no(int *a, int b){
  return __forza_amo_r_or32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_or64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.or64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_or64rem_no(long int *a, long int b){
  return __forza_amo_r_or64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.xor8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_xor8rem_no(char *a, char b){
  return __forza_amo_r_xor8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.xor16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_xor16rem_no(short *a, short b){
  return __forza_amo_r_xor16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.xor32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_xor32rem_no(int *a, int b){
  return __forza_amo_r_xor32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_xor64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.xor64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_xor64rem_no(long int *a, long int b){
  return __forza_amo_r_xor64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smax8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smax8rem_no(char *a, char b){
  return __forza_amo_r_smax8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smax16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smax16rem_no(short *a, short b){
  return __forza_amo_r_smax16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smax32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smax32rem_no(int *a, int b){
  return __forza_amo_r_smax32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smax64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smax64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smax64rem_no(long int *a, long int b){
  return __forza_amo_r_smax64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umax8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umax8rem_no(unsigned char *a, char b){
  return __forza_amo_r_umax8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umax16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umax16rem_no(unsigned short *a, short b){
  return __forza_amo_r_umax16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umax32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umax32rem_no(unsigned int *a, int b){
  return __forza_amo_r_umax32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umax64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umax64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umax64rem_no(unsigned long int *a, long int b){
  return __forza_amo_r_umax64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.smin8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_smin8rem_no(char *a, char b){
  return __forza_amo_r_smin8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.smin16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_smin16rem_no(short *a, short b){
  return __forza_amo_r_smin16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.smin32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_smin32rem_no(int *a, int b){
  return __forza_amo_r_smin32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_smin64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.smin64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_smin64rem_no(long int *a, long int b){
  return __forza_amo_r_smin64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.umin8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_umin8rem_no(unsigned char *a, char b){
  return __forza_amo_r_umin8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.umin16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_umin16rem_no(unsigned short *a, short b){
  return __forza_amo_r_umin16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.umin32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_umin32rem_no(unsigned int *a, int b){
  return __forza_amo_r_umin32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_umin64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.umin64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_umin64rem_no(unsigned long int *a, long int b){
  return __forza_amo_r_umin64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs8rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i8 @llvm.riscv.forza.amo.r.thrs8rem.no(ptr [[RS1:%.*]], i8 [[RS2:%.*]])
char amo_r_thrs8rem_no(char *a, char b){
  return __forza_amo_r_thrs8rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs16rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i16 @llvm.riscv.forza.amo.r.thrs16rem.no(ptr [[RS1:%.*]], i16 [[RS2:%.*]])
short amo_r_thrs16rem_no(short *a, short b){
  return __forza_amo_r_thrs16rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i32 @llvm.riscv.forza.amo.r.thrs32rem.no(ptr [[RS1:%.*]], i32 [[RS2:%.*]])
int amo_r_thrs32rem_no(int *a, int b){
  return __forza_amo_r_thrs32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_thrs64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call i64 @llvm.riscv.forza.amo.r.thrs64rem.no(ptr [[RS1:%.*]], i64 [[RS2:%.*]])
long int amo_r_thrs64rem_no(long int *a, long int b){
  return __forza_amo_r_thrs64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.fadd32u(ptr [[RS1:%.*]], float [[RS2:%.*]])
void amo_r_fadd32u(float *a, float b){
  __forza_amo_r_fadd32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.fadd64u(ptr [[RS1:%.*]], double [[RS2:%.*]])
void amo_r_fadd64u(double *a, double b){
  __forza_amo_r_fadd64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fadd32migr.nn(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fadd32migr_nn(float *a, float b){
  return __forza_amo_r_fadd32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fadd64migr.nn(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fadd64migr_nn(double *a, double b){
  return __forza_amo_r_fadd64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fadd32migr.on(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fadd32migr_on(float *a, float b){
  return __forza_amo_r_fadd32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fadd64migr.on(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fadd64migr_on(double *a, double b){
  return __forza_amo_r_fadd64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fadd32migr.no(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fadd32migr_no(float *a, float b){
  return __forza_amo_r_fadd32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fadd64migr.no(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fadd64migr_no(double *a, double b){
  return __forza_amo_r_fadd64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fadd32rem.nn(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fadd32rem_nn(float *a, float b){
  return __forza_amo_r_fadd32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fadd64rem.nn(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fadd64rem_nn(double *a, double b){
  return __forza_amo_r_fadd64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fadd32rem.on(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fadd32rem_on(float *a, float b){
  return __forza_amo_r_fadd32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fadd64rem.on(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fadd64rem_on(double *a, double b){
  return __forza_amo_r_fadd64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fadd32rem.no(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fadd32rem_no(float *a, float b){
  return __forza_amo_r_fadd32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fadd64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fadd64rem.no(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fadd64rem_no(double *a, double b){
  return __forza_amo_r_fadd64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.fsub32u(ptr [[RS1:%.*]], float [[RS2:%.*]])
void amo_r_fsub32u(float *a, float b){
  __forza_amo_r_fsub32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.fsub64u(ptr [[RS1:%.*]], double [[RS2:%.*]])
void amo_r_fsub64u(double *a, double b){
  __forza_amo_r_fsub64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsub32migr.nn(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsub32migr_nn(float *a, float b){
  return __forza_amo_r_fsub32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsub64migr.nn(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsub64migr_nn(double *a, double b){
  return __forza_amo_r_fsub64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsub32migr.on(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsub32migr_on(float *a, float b){
  return __forza_amo_r_fsub32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsub64migr.on(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsub64migr_on(double *a, double b){
  return __forza_amo_r_fsub64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsub32migr.no(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsub32migr_no(float *a, float b){
  return __forza_amo_r_fsub32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsub64migr.no(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsub64migr_no(double *a, double b){
  return __forza_amo_r_fsub64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsub32rem.nn(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsub32rem_nn(float *a, float b){
  return __forza_amo_r_fsub32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsub64rem.nn(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsub64rem_nn(double *a, double b){
  return __forza_amo_r_fsub64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsub32rem.on(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsub32rem_on(float *a, float b){
  return __forza_amo_r_fsub32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsub64rem.on(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsub64rem_on(double *a, double b){
  return __forza_amo_r_fsub64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsub32rem.no(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsub32rem_no(float *a, float b){
  return __forza_amo_r_fsub32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsub64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsub64rem.no(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsub64rem_no(double *a, double b){
  return __forza_amo_r_fsub64rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.fsubr32u(ptr [[RS1:%.*]], float [[RS2:%.*]])
void amo_r_fsubr32u(float *a, float b){
  __forza_amo_r_fsubr32u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64u(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  call void @llvm.riscv.forza.amo.r.fsubr64u(ptr [[RS1:%.*]], double [[RS2:%.*]])
void amo_r_fsubr64u(double *a, double b){
  __forza_amo_r_fsubr64u(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsubr32migr.nn(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsubr32migr_nn(float *a, float b){
  return __forza_amo_r_fsubr32migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64migr_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsubr64migr.nn(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsubr64migr_nn(double *a, double b){
  return __forza_amo_r_fsubr64migr_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsubr32migr.on(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsubr32migr_on(float *a, float b){
  return __forza_amo_r_fsubr32migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64migr_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsubr64migr.on(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsubr64migr_on(double *a, double b){
  return __forza_amo_r_fsubr64migr_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsubr32migr.no(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsubr32migr_no(float *a, float b){
  return __forza_amo_r_fsubr32migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64migr_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsubr64migr.no(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsubr64migr_no(double *a, double b){
  return __forza_amo_r_fsubr64migr_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsubr32rem.nn(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsubr32rem_nn(float *a, float b){
  return __forza_amo_r_fsubr32rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64rem_nn(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsubr64rem.nn(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsubr64rem_nn(double *a, double b){
  return __forza_amo_r_fsubr64rem_nn(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsubr32rem.on(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsubr32rem_on(float *a, float b){
  return __forza_amo_r_fsubr32rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64rem_on(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsubr64rem.on(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsubr64rem_on(double *a, double b){
  return __forza_amo_r_fsubr64rem_on(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr32rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call float @llvm.riscv.forza.amo.r.fsubr32rem.no(ptr [[RS1:%.*]], float [[RS2:%.*]])
float amo_r_fsubr32rem_no(float *a, float b){
  return __forza_amo_r_fsubr32rem_no(a,b);
}

// RV64XFORZA-LABEL: @amo_r_fsubr64rem_no(
// RV64XFORZA-NEXT:  entry:
// RV64XFORZA-NEXT:  [[TMP0:%.*]] = call double @llvm.riscv.forza.amo.r.fsubr64rem.no(ptr [[RS1:%.*]], double [[RS2:%.*]])
double amo_r_fsubr64rem_no(double *a, double b){
  return __forza_amo_r_fsubr64rem_no(a,b);
}

